### PR TITLE
Remove pinned requirements

### PR DESCRIPTION
**Pull request by lababidi**

### CODE REVIEW

**Comment by Brett55** [comment]
This is an anti pattern, having open dependencies exposes breaking changes

**Comment by nricklin** [comment]
What's the reason to un-pin?  I agree it's an anti-pattern.

**Comment by lababidi** [comment]
It was breaking my other installations. I understand the dependency
pinning, but gbdxtools and gbdx-auth needs to play nicely with other
packages installed in my projects.

**Comment by nricklin** [comment]
Perhaps you can find a way to do something like ```package>=0.2,<0.3```.  The main thing we want to protect against is new versions that break or change functionality.

**Comment by lababidi** [comment]
Agreed. if you took the current branch I have, would it pass your CI
build+test?

**Comment by Brett55** [comment]
Who are you talking to?

On Fri, Mar 16, 2018 at 12:31 PM, Mahmoud Lababidi <notifications@github.com

**Comment by lababidi** [comment]
The owners of this package. Or anyone responding to this PR. Is continuous
integration set up?

**Comment by Brett55** [comment]
Gbdxtools relies on gbdx auth the most so that would be the place to verify
a build. I don't think unpinning deps is a good idea

**Comment by lababidi** [comment]
Most packages I dug into have dependencies that are mostly open (>). Some
have a few dependencies with limits on max version as well.
The reason for this is because as a library, you can't restrict the
application developer using your library (gbdx-auth, gbdxtools) on what
packages they can use in their application.
I assume, this is a library meant to be used by many applications
(ideally).

I'm not sure where anti-pattern belongs in this discussion. I guess I'm not
that experienced to sniff these things out.

**Comment by nricklin** [comment]
ok looking into it, it looks like best practice is to unpin a library, but pin at the application level (or final deploy level).

I'll ship this.

**Comment by Brett55** [comment]
Nate theres no opportunity to pin at a deploy level

**Pull request merged**
