### PR TITLE
Added support for pulling creds from envvars.

### PR DESCRIPTION
**Pull request by youngpm**
This is more secure in the "12 factor app" view of the world. Also
updated the readme and the requirements.

This "should" be a backwards compatible change, please take a look!

### CODE REVIEW

**Comment by youngpm** [comment]
Oh and I fixed the token refresh.  Previously, I wasn't updating the expiration time when reading it out of the ini file, now it does.

**Comment by svohara** [comment]
Can you make similar modifications to gbdx-py? Should we have that library subsume this one, or keep them separately maintained?

**Comment by youngpm** [comment]
@svohara not sure if we should merge the two, gbdx-auth is used by a few people and it has minimal requirements, don't want to break anyone's stuff. 

My plan is to get gbdx-auth py3 compatible and put it on pypi.  If we do that, then we can just make gbdx-py have gbdx-auth as a dependency and remove the auth piece from gbdx-py all together.  What do you think?

**Comment by nricklin** [comment]
I think gbdx-py using gbdx-auth as a dependency is a good way to go

**Comment by svohara** [comment]
Ok, My opinion is that a single, combined gbdx-py library that includes gbdx_auth as a module is the way to go. And assuming the other modules don't require additional dependencies, then it's still "lightweight". But maybe making this consolidation is too soon for now, and I defer to the majority vote here. :) So for now, they are separately maintained.

Either way, there are changes in the gbdx_auth.py module in the gbdx-py code that we may wish to port. 1) Fix for people given apikeys instead of client_id+client_secret pairs. 2) The returned session now has JSON as the default content type, so the REST api works by default when a POST is called using json contents. Otherwise, the user has to modify the headers for each call.

If we can support all the changes in this repo and then remove the redundant code from gbdx-py, it would be cleaner. Then we have to mark the dependency and create setup code for gbdx-py that pulls in the gbdx_auth library on installation, etc.

**Comment by youngpm** [comment]
I'll port what you've got here (https://github.com/TDG-Platform/gbdx-py/blob/master/gbdx/gbdx_auth.py) and do another pull request.  Should be super easy.

So looking here (https://github.com/TDG-Platform/gbdx-py/blob/master/gbdx/gbdx_auth.py#L85-L92) the api key is just the client id and secret concatenated with a colon?  And the secret can apparently have colons in it as well?

**Comment by svohara** [comment]
Yes, it seems goofy to me. If you unpack the apikey, you get a "client id" and "client secret", and it works, but it may not be the "real" client id because there may be more than one colon in the encoded api key. I think what OAuth2 does under the hood is to pack the client_id and client_secret into a single colon-separated base64 key. Thus given the key, you should be able to use it directly...but I didn't see how to do that with the provided interface.

**Pull request merged**
